### ISSUE TITLE
"!" symbol is Rotation 90 degree to0

### ISSUE THREAD

**Issue by rukit24** [MyK00L/tategakifont#5]
Can you take a look at the code to check please. In my case i appied your code to generate tategakifont very well. But when reading in Korreader i notice that the "!" is rotated 90 degree to but in your htlm test i saw it is normally ! without rotation.

**Comment by MyK00L** [comment]
Maybe it's because one is the fullwidth "！" while one is the halfwidth "!".
If it's the first, it should appear upright, while the second should appear sideways.
I've added the halfwidth one as well in the html for comparison.
If you don't think this is the problem, please tell me the font you're using.

**Comment by rukit24** [comment]
I am using Klee One. Maybe as you said  i have't seen the fullwidth in my reading.

**Comment by MyK00L** [comment]
It seems to work as intended on your font, so it's probably a halfwidth character in your reading.
I've added the option `--half-to-full` to replace halfwidth glyphs with fullwidth ones, if enabled all english letters and punctuation will look upright regardless.
